apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-ms
  labels:
    app: answer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer-ms
  template:
    metadata:
      labels:
        app: answer-ms
    spec:
      containers:
        - name: answer-ms
          image: islamahmad/eaproj-answerms:1.0.10

          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-answerms:1.0.10"

            - name: SERVER_PORT
              value: "8080"

            #MONGODB
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: answer-ms
                  key: MONGODB_PASS

          envFrom:
            - configMapRef:
                name: answer-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global

